\mainmatter

# (PART) 初识 R Markdown {.unnumbered}

# R Markdown概述 {#rmarkdown-intro}

## R Markdown 的渊源 {#rmarkdown-source}

在过去的十多年间，R 语言发展的十分迅猛，这其中就包括了 R Markdown。这段往事可能要追溯到 2007 年。那时候，还在中国人民大学上学的谢益辉开始使用 **Sweave**，并沉迷于此无法自拔。不仅自己在写作业的时候尽可能的使用 Sweave，还持之以恒地向同学们兜售。Sweave 的命名是 S + weave，前者指的是 S 语言，这是 R 语言的前身，后者含义即“编织”。Sweave 之所以受到谢同学的追捧，正是因为它可以将某些东西编织起来——代码和代码执行后的结果。直到今天，Sweave 仍然是 RStudio 中从 Rnw 文档生成 PDF 的重要工具之一。

笔者猜测，对 Sweave 的痴迷也让谢益辉深受其某些不好用特性的苦。这可能是促使他开发 knitr [@R-knitr] 的源动力[^knitr-in-the-beginning]。knitr 的编写受 Sweave 影响很大，就连名字的逻辑似乎都是一样的。knitr 是 knit + R，前者的意思仍然是“编织”，后者则是 R 语言。而且 knitr 的读音听起来就跟另一个单词“neater”是一样的，给人一种更加灵巧的感觉！

[^knitr-in-the-beginning]: 谢益辉曾经说过自己“受过几年 Sweave 折磨，最后才揭竿而起。”

knitr 是 CRAN 中依赖最多的包之一（<https://blog.csdn.net/qq_18055167/article/details/104374971>），与另外的 4600 多个包存在依赖、被依赖、建议安装等关系。rmarkdown 排第四，与 CRAN 中的其它软件包有超过 3600 种各类联系。

虽然 knitr 的编写受到 Sweave 影响，但模块化程度更高，扩展方便，支持文档类型也更多（Sweave 主要用于 LaTeX 文档）。与此同时，Sweave 中的一些优良特性也被 knitr 继承了下来，例如行内代码。从这个意义上说，Sweave 是 knitr 的“爸爸”。而 knitr 也有很多孩子，其中的一个就是 rmarkdown [@R-rmarkdown]，knitr 和 rmarkdown 包都是实现 R Markdown 功能的基础设施。

回过头来看，当年谢益辉写 knitr 包只是为了更方便地完成自己的作业，而 knitr 可以写作业，也可以用来写数据分析报告，碰巧做数据分析的人都要写报告。在 knitr 之前有 Sweave，他用了好几年，刚开始觉得很兴奋，用着用着就到了四处碰壁的状态，觉得**一个绝妙的想法**不幸得到了一个蹩脚的实现。直到后来决定推倒重写算了。

在谈到开发经验时，他谈到：

> 不用看远方，就看你自身能感受到的非常痛苦的问题。如果你能解决自己的一个非常痛而且频繁出现的痛点，那么有相当大的概率你也会造福别人，从而产生重大影响。
> 
> 解决的问题越基础越好，比如大家常用工作流程中必经的一步，这一步也许已经有现成解决方案了，但每个月总有那么三十来天让你对这个解决方案感到不满。越基础的问题，影响的人群就越广。
>   —— 谢益辉（2018）


2021 年，在巴西举行的 R-Day 会议上，谢益辉曾经官方解释过这段历史，感兴趣的读者不妨去看一下“Knitr 亲述历史”：<https://slides.yihui.org/2021-Brazilian-R-Day.html>。


### R Markdown 与文学化编程 {#r-markdown-literate-programming}

初学者可能会认为 rmarkdown 软件包就是 R Markdown，但是事实并非如此。R Markdown 是文学化编程的一种实现方式，她包含了一系列的工具和软件包，而本书只能介绍其中有限的几个。文学化编程就是前面刚刚提及的**一个绝妙的想法**，她是高德纳（Knuth, Donald E.）在 1984 年提出的编程方法，旨在取代结构化编程范型。文学编程范型让程序员用他们自己思维内在的逻辑和流程所要求的顺序开发程序，而且用人类日常使用的语言写出来，就好像一篇文章一样。

文学化编程本来是为了编程和写文档两个目的而生的，想法看起来很好，但其实这两件事情都没有很方便地完成。编程通常就是代码加注释，大家都熟悉这个套路，没有人在代码之间长篇大论写文档来解释这里的代码在干什么；文档通常也是相对独立于代码的。嵌入了代码的文档或嵌入了文档的代码对于一般读者来说都不易读，所以总而言之，文学化编程本来是一个坏主意。

然而，文学化编程范式却无意间影响了可重复的科学研究。它不适合写代码，但适合写数据分析报告。数据分析比纯写代码有趣，因为结果经常是图文并茂，但数据分析的过程往往是一团糟，这里就是文学化编程的想法能发力的地方。代码嵌入文档中的目的不是为了单纯的编译，而是为了出结果（图表等）。代码和文档结合之后，也便于动态控制输出结果[^literate-programming]。

[^literate-programming]: 上述两段文字摘自谢益辉博客 2014 年 1 月 3 日的一篇文章，有删改。原文见：<https://yihui.org/cn/2014/01/literate-programming/>。

## 以案例形式初识 R Markdown {#rmarkdown-example}

### 数据分析报告 {#example-report}

### 交互笔记本 {#example-note}

### 个人简历 {#example-cv}

### 网站 {#example-resume}

### 幻灯片 {#example-ppt}

### 交互报表 {#example-forms}

### 动态文档 {#example-dynamic}
