---
title: 通过呈现函数来设置输出参数
runtime: shiny
output: html_document
---

这个交互式 Rmd 文档使用了 `outputArgs`
参数，并且现在可用于所有 Shiny `render` 函数。 举个例子，这可以让你通过 `renderImage` 设置 `imageOutput` 的参数。 意味着你不必为了刷过图像而创建 `ui` 对象。 注意，这仅适用于交互式  Rmd 期间的 Shiny 代码片段（不适用于嵌入式完整应用程序——你需要调用 `shinyApp` 才能运行的应用程序）。 

## 刷过图像(并存储数据)

```{r setup, echo=FALSE}
library(datasets)

generateImage = function() {
  outfile = tempfile(fileext = '.png')
  png(outfile)
  par(mar = c(0,0,0,0))
  image(volcano, axes = FALSE)
  contour(volcano, add = TRUE)
  dev.off()
  list(src = outfile)
}
```

```{r image}
renderImage({
  generateImage()
}, deleteFile = TRUE, 
   outputArgs = list(brush = brushOpts(id = "plot_brush"),
                     width = "250",
                     height = "250px")
)
```

以下是发送到服务器的一些信息: (刷过图像以更改数据)

```{r brush info}
renderText({ 
  print(input$plot_brush)
  brush = input$plot_brush
  paste0("xmin: ", brush$xmin, "; ",
         "xmax: ", brush$xmax, "; ",
         "ymin: ", brush$ymin, "; ",
         "ymax: ", brush$ymax)
})
```

---

###  调整图片


```{r plot}
renderPlot({ 
  plot(cars) 
}, outputArgs = list(width = "75%", 
                     height = "250px")
)
```
